In [14]:
import pandas as pd
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
orders.head()
orders.head(10)
orders.shape
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [13]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [3]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [4]:
missing_percentage = (orders.isnull().sum() / len(orders)) * 100
missing_percentage

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [5]:
missing_percentage = (orders.isnull().sum()/len(orders))*100

missing_percentage.round(2)

order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
dtype: float64

In [6]:
missing_data = pd.DataFrame({
    "Missing Values": orders.isnull().sum(),
    "Percentage": missing_percentage.round(2)
})

missing_data

                               Missing Values  Percentage
order_id                                    0        0.00
customer_id                                 0        0.00
order_status                                0        0.00
order_purchase_timestamp                    0        0.00
order_approved_at                         160        0.16
order_delivered_carrier_date             1783        1.79
order_delivered_customer_date            2965        2.98
order_estimated_delivery_date               0        0.00

In [7]:
orders.duplicated().sum()

0

In [8]:
orders.duplicated(subset=["order_id"]).sum()

0

#### Duplicate Check

- Checked for duplicate rows using `duplicated()`.
- Result: No duplicate rows were found.
- Verified that `order_id` is unique using `duplicated(subset=["order_id"])`.
- Result: No duplicate order IDs were found.
- Conclusion: No duplicate records need to be removed from the orders dataset.  ###

In [16]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [17]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

In [18]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: datetime64[ns](1), object(7)
memory usage: 6.1+ MB

In [20]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

In [21]:
for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [22]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [23]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [24]:
orders[orders["order_delivered_customer_date"].isnull()][
    "order_status"
].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

### Observation

- The majority of missing `order_delivered_customer_date` values are associated with cancelled or unavailable orders.
- These missing values are expected due to the order lifecycle and do not represent data quality issues.
- Therefore, these values will be retained rather than filled or removed.

In [25]:
orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

## Missing Delivery Date Analysis

### Observation

- There are 2,965 missing values in `order_delivered_customer_date`.
- Most missing values belong to orders with statuses such as `shipped`, `canceled`, `unavailable`, `processing`, `created`, and `approved`.
- These missing values are expected because such orders were either not delivered or still in progress.
- Only 8 orders marked as `delivered` have a missing delivery date. These records require further investigation before any cleaning decision is made.

### Decision

- Retain the expected missing values.
- Investigate the 8 delivered orders separately instead of removing all rows with missing delivery dates.

In [26]:
delivery_data = orders[
    orders["order_delivered_customer_date"].notnull()
]

### Decision on Delivered Orders with Missing Delivery Date

Eight records have an order status of `delivered` but are missing the `order_delivered_customer_date`.

Since the actual delivery dates are unknown, these values cannot be accurately imputed. Removing the records would also result in the loss of valid order information.

**Decision:**
- Retain these records in the dataset.
- Exclude them only from analyses that require the delivery date (e.g., delivery time calculation).

In [30]:
delivery_data = orders[
    orders["order_delivered_customer_date"].notnull()
].copy()

In [31]:
delivery_data["delivery_days"] = (
    delivery_data["order_delivered_customer_date"]
    - delivery_data["order_purchase_timestamp"]
).dt.days

In [33]:
import os

os.makedirs("data/cleaned", exist_ok=True)

In [34]:
orders.to_csv("data/cleaned/orders_cleaned.csv", index=False)

- Converted all date-related columns from object to datetime format.
- Prepared the dataset for feature engineering and exploratory analysis.